### ISSUE TITLE
Use a monorepo?

### ISSUE THREAD

**Issue by aaronshaf** [staltz/callbag-basics#10]
A centralized repo (from which all your packages are published) might be a better fit for this.

**Comment by staltz** [comment]
Hi Aaron :)
I really don't agree because that's what I've done in the past, and all these utilities don't *need* to agree on anything else other than the spec itself. Also as a monorepo there could be a fake impression that operators in the monorepo are somewhat more official. All utilities should be on the same level of appreciation, at least in the beginning of an ecosystem of utilities.

**Comment by aaronshaf** [comment]
Totally appreciate that 👍 

PS Love your love for all things decentralized.
